version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
    
conda:
  environment: .binder/environment.yml  # or your custom YAML path

sphinx:
  configuration: source/conf.py

python:
  install:
    - method: pip
      path: .
