name: gracefo-env
channels:
  - conda-forge
  - defaults
dependencies:
  # Core Python
  - python=3.9
  - pip
  - ipykernel
  - notebook             # Jupyter notebook interface
  - jupyterlab           # Optional lab interface
  
  # Numerical & Analysis
  - numpy                # Core array library
  - pandas               # Data handling
  - statsmodels          # Statistical modeling (from anaconda)

  # Geospatial & NetCDF
  - gdal=3.6.2           # Geospatial data abstraction library
  - cartopy              # Map plotting
  - shapefile            # PyShp for handling shapefiles
  - netcdf4              # NetCDF support
  - xarray=2023.1.0      # Labeled N-D arrays
  - fsspec               # File system interface (S3, etc.)
  - s3fs                 # For reading data from AWS S3

  - sphinx_rtd_theme
  - alabaster=0.7.12 #this and following few copied from ecco project requirements.txt
  - babel=2.11.0
  - certifi=2022.12.7
  - charset-normalizer=2.1.1
  - docutils=0.19
  - idna=3.4
  - imagesize=1.4.1
  - ipykernel=6.23.0
  - jinja2=3.1.2
  - markupsafe=2.1.1
  - myst-parser=1.0.0
  - nbsphinx=0.9.1
  - packaging=22.0
  - pandoc=2.3     # from sphinx website
  - pygments=2.13.0
  - pytz=2022.7
  - requests=2.28.1
  - snowballstemmer=2.2.0
  - sphinx=5.3.0
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=2.0.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.5
  - sphinx-rtd-theme=0.4.3
  - urllib3=1.26.13


